<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGbkjmxN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGbkjmxN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGbkjmxN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGbkjmxN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGbkjmxN\App_KernelDevDebugContainer([
    'container.build_hash' => 'GbkjmxN',
    'container.build_id' => 'c2f3db87',
    'container.build_time' => 1611860027,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGbkjmxN');
